#ifndef ROGALUNAWEBSERVER_GLOBAL_H
#define ROGALUNAWEBSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNAWEBSERVER_LIBRARY)
#define ROGALUNAWEBSERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNAWEBSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNAWEBSERVER_GLOBAL_H
