#ifndef ROGALUNACONFIGREADER_GLOBAL_H
#define ROGALUNACONFIGREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNACONFIGREADER_LIBRARY)
#define ROGALUNACONFIGREADER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNACONFIGREADER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNACONFIGREADER_GLOBAL_H
