#ifndef ROGALUNACLOUDDRIVESERVER_GLOBAL_H
#define ROGALUNACLOUDDRIVESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNACLOUDDRIVESERVER_LIBRARY)
#define ROGALUNACLOUDDRIVESERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNACLOUDDRIVESERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNACLOUDDRIVESERVER_GLOBAL_H
