#ifndef ROGALUNADATABASESERVER_GLOBAL_H
#define ROGALUNADATABASESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNADATABASESERVER_LIBRARY)
#define ROGALUNADATABASESERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNADATABASESERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNADATABASESERVER_GLOBAL_H
