#ifndef ROGALUNALIBRARYSERVER_GLOBAL_H
#define ROGALUNALIBRARYSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNALIBRARYSERVER_LIBRARY)
#define ROGALUNALIBRARYSERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNALIBRARYSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNALIBRARYSERVER_GLOBAL_H
