#ifndef ROGALUNASTORAGESERVER_GLOBAL_H
#define ROGALUNASTORAGESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNASTORAGESERVER_LIBRARY)
#define ROGALUNASTORAGESERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNASTORAGESERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNASTORAGESERVER_GLOBAL_H
