#ifndef ROGALUNAACCOUNTSERVER_GLOBAL_H
#define ROGALUNAACCOUNTSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNAACCOUNTSERVER_LIBRARY)
#define ROGALUNAACCOUNTSERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNAACCOUNTSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNAACCOUNTSERVER_GLOBAL_H
