#ifndef QJSONWEBTOKEN_GLOBAL_H
#define QJSONWEBTOKEN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QJSONWEBTOKEN_LIBRARY)
#define QJSONWEBTOKEN_EXPORT Q_DECL_EXPORT
#else
#define QJSONWEBTOKEN_EXPORT Q_DECL_IMPORT
#endif

#endif // QJSONWEBTOKEN_GLOBAL_H
