#ifndef ROGALUNAHTTPSERVER_GLOBAL_H
#define ROGALUNAHTTPSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROGALUNAHTTPSERVER_LIBRARY)
#define ROGALUNAHTTPSERVER_EXPORT Q_DECL_EXPORT
#else
#define ROGALUNAHTTPSERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // ROGALUNAHTTPSERVER_GLOBAL_H
